export default {
  USER_CREATED: 'User created successfully',
  ADMIN_CREATED:"Admin created successfully",
  UNAUTHORIZED: 'Unauthorized access',
  MISSING_FIELDS: 'Required fields are missing',
  USERS_FETCHED: 'Users fetched successfully',
  AUTH_TOKEN_REQUIRED: 'Authorization token are required',
  ALREADY_REGISTERED: 'User already registered',
  ALREADY_REGISTERED_ADMIN: 'Admin already registered',
  LOGIN:'Login successful',
  NOT_FOUND: 'User Not found',
  MISSING_ADMIN_ID: 'Admin ID is required',
  INVALID_CREDENTIALS: 'Invalid username or password',
  INVALID_LOGIN:"Invalid email or password",
  DB_CONNECTION_FAILED: 'Failed to connect to the database',
  NO_ADMINS_FOUND: 'No admins found',
  USER_DELETED:'User deleted successfully',
  FORGOT_PASSWORD_EMAIL_SENT: 'Forgot password email sent successfully',
  PASSWORD_RESET_SUCCESS: 'Password reset successfully',
  Reset_password_email_sent: 'Reset password email sent successfully',
  PASSWORD_UPDATED: 'Password updated successfully',
  SMTP_UPDATED: 'SMTP settings updated successfully',
  SMTP_VERIFIED: 'SMTP settings verified successfully',
  SMTP_UPDATE_FAILED: 'SMTP settings update failed',
  SMTP_NOT_FOUND: 'SMTP settings not found',
  SMTP_PORT_MISMATCH: 'SMTP port mismatch',
  
};
